### ISSUE TITLE
Feature: Favoriting

### ISSUE THREAD

**Issue by TheHollidayInn** [SoftwareEngineeringDaily/SEDaily-Android#19]
This is now on our API, so we should add :D

**Comment by samuelrey** [comment]
I'd like to pick this up! :)

**Comment by TheHollidayInn** [comment]
Go for it!

**Comment by samuelrey** [comment]
I've made a couple quick mocks. The items in orange are being added.
![1-0_home](https://user-images.githubusercontent.com/9016717/32637667-09234704-c570-11e7-98e9-707d3dd74aae.png)
![2-0_podcastdetails](https://user-images.githubusercontent.com/9016717/32637671-0c2fc95e-c570-11e7-9d18-544189229fe3.png)

**Comment by samuelrey** [comment]
Another thing I could think to add is a cache of the bookmarked posts so that:
- the user sees that their action persists
- the app makes the proper API call when the bookmark button is pressed
- the app doesn't need to make as many API calls to check if the post has been bookmarked

Could someone help me with this part?

**Comment by TheHollidayInn** [comment]
Coming up in next release.
